### Text Mining Processing Procedures
1. Tokenization
2. Preprocessing
3. Stop Words
4. Summary

### Example 1 (BOW)

In [3]:
import collections

In [4]:
stop_words = ['\n', 'or', 'are', 'they', 'i', 'I', 'some', 'by', '-', 'even', 'the', 'a', 'an', 'to', 'and', 'what', 'when', 'which', 'how', 'can', 'could', 'may', 'might', 'in', 'on', 'for', 'of', 'that', 'with', 'as', 'far', 'its', 'this', 'these', 'other', 'more', 'have', 'not', 'had', 'has', 'at', 'only', 'most'] 

In [ ]:
maxlen = 1000

word_freqs = collections.Counter()
with open('data.txt') as f:
    for line in f:
        words = line.lower().split(' ')
        if len(words) > maxlen:
            maxlen = len(words)
        for word in words:
            if word not in stop_words:
                word_freqs[word] += 1

print(word_freqs.most_common(20))

### Example 2 (TF-IDF)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np

In [7]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

In [9]:
Vectorizer = CountVectorizer()
X = Vectorizer.fit_transform(corpus)

word = Vectorizer.get_feature_names_out()
print("Vocabulary: ", word)

Vocabulary:  ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [10]:
print("BOW=\n", X.toarray())

BOW=
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [12]:
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
print("TF-IDF=\n", np.around(tfidf.toarray(), 4))

TF-IDF=
 [[0.     0.4698 0.5803 0.3841 0.     0.     0.3841 0.     0.3841]
 [0.     0.6876 0.     0.2811 0.     0.5386 0.2811 0.     0.2811]
 [0.5118 0.     0.     0.2671 0.5118 0.     0.2671 0.5118 0.2671]
 [0.     0.4698 0.5803 0.3841 0.     0.     0.3841 0.     0.3841]]


In [15]:
from sklearn.metrics.pairwise import cosine_similarity
print("Cosine similarity: \n", cosine_similarity(tfidf[-1], tfidf[::-1], dense_output = False))

Cosine similarity: 
   (0, 3)	1.0000000000000002
  (0, 2)	0.6469256761082494
  (0, 1)	0.30777186787740507
  (0, 0)	1.0000000000000002


### Example 3 (NLTK - Text Preprocessing)

In [28]:
import nltk
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/kao900531/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kao900531/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [19]:
text = "Today is a great day. It is even better than yesterday. And yesterday was the best day ever." + \
         " I am looking forward to tomorrow. Tomorrow will be even better than today. I am happy."
print("Text: ", text)

Text:  Today is a great day. It is even better than yesterday. And yesterday was the best day ever. I am looking forward to tomorrow. Tomorrow will be even better than today. I am happy.


In [20]:
nltk.sent_tokenize(text)

['Today is a great day.',
 'It is even better than yesterday.',
 'And yesterday was the best day ever.',
 'I am looking forward to tomorrow.',
 'Tomorrow will be even better than today.',
 'I am happy.']

In [21]:
nltk.word_tokenize(text)

['Today',
 'is',
 'a',
 'great',
 'day',
 '.',
 'It',
 'is',
 'even',
 'better',
 'than',
 'yesterday',
 '.',
 'And',
 'yesterday',
 'was',
 'the',
 'best',
 'day',
 'ever',
 '.',
 'I',
 'am',
 'looking',
 'forward',
 'to',
 'tomorrow',
 '.',
 'Tomorrow',
 'will',
 'be',
 'even',
 'better',
 'than',
 'today',
 '.',
 'I',
 'am',
 'happy',
 '.']

In [22]:
# Stemming
text = "My system keeps crashing his crashed yesterday, ours crashes daily"
ps = nltk.porter.PorterStemmer()
' '.join([ps.stem(word) for word in text.split()])

'my system keep crash hi crash yesterday, our crash daili'

In [25]:
# Lemmatization
text = "My system keeps crashing his crashed yesterday, ours crashes daily"
lem = nltk.WordNetLemmatizer()
' '.join([lem.lemmatize(word) for word in text.split()])

'My system keep crashing his crashed yesterday, ours crash daily'

In [32]:
import string

print("Punctuation: ", string.punctuation)

text = "Today is a great day. It is even better than yesterday. And yesterday was the best day ever." + \
        " And yesterday was the best day ever"

stopword_list = set(nltk.corpus.stopwords.words('english') + list(string.punctuation))

def remove_stopwords(text, is_lower_case = False):
    if is_lower_case:
        text = text.lower()
    tokens = nltk.word_tokenize(text)
    tokens = [token.strip() for token in tokens]
    filtered_tokens = [token for token in tokens if token not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text, filtered_tokens

filtered_text, filtered_tokens = remove_stopwords(text)
filtered_text

Punctuation:  !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


'Today great day It even better yesterday And yesterday best day ever And yesterday best day ever'

In [33]:
# BOW model
with open('./news.txt', 'r+', encoding='utf-8') as f:
    text = f.read()

filtered_text, filtered_tokens = remove_stopwords(text, is_lower_case = True)

import collections
word_freqs = collections.Counter()

for word in filtered_tokens:
    word_freqs[word] += 1
print(word_freqs.most_common(20))

FileNotFoundError: [Errno 2] No such file or directory: './news.txt'

In [34]:
# Regular expression
lem = nltk.WordNetLemmatizer()

def remove_stopwords_regex(text, is_lower_case = False):
    if is_lower_case:
        text = text.lower()
    tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+') # \w+ means any word character (equal to [a-zA-Z0-9_]) (Alphanumeric)
    tokens = tokenizer.tokenize(text)
    tokens = [lem.lemmatize(token.strip()) for token in tokens]
    filtered_tokens = [token for token in tokens if token not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text, filtered_tokens

filtered_text, filtered_tokens = remove_stopwords_regex(text, is_lower_case = True)
word_freqs = collections.Counter()

for word in filtered_tokens:
    word_freqs[word] += 1
print(word_freqs.most_common(20))

[('day', 3), ('yesterday', 3), ('wa', 2), ('best', 2), ('ever', 2), ('today', 1), ('great', 1), ('even', 1), ('better', 1)]


### Example 4 (Find Synonyms & Antonyms)

In [54]:
import nltk
from nltk import pos_tag
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/kao900531/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [43]:
# Find Synonyms
synonyms = nltk.corpus.wordnet.synsets('love')
synonyms


[Synset('love.n.01'),
 Synset('love.n.02'),
 Synset('beloved.n.01'),
 Synset('love.n.04'),
 Synset('love.n.05'),
 Synset('sexual_love.n.02'),
 Synset('love.v.01'),
 Synset('love.v.02'),
 Synset('love.v.03'),
 Synset('sleep_together.v.01')]

In [45]:
print(synonyms[0].definition())
print(synonyms[0].examples())

a strong positive emotion of regard and affection
['his love for his work', 'children need a lot of love']


In [46]:
# Find Antonyms
antonyms = []
for syn in nltk.corpus.wordnet.synsets('ugly'):
    for i in syn.lemmas():
        if i.antonyms():
            antonyms.append(i.antonyms()[0].name())
antonyms

['beautiful']

In [56]:
# POS tagging
text = "I am a human being, capable of doing terrible things"
sentence = nltk.word_tokenize(text)

for sent in sentence:
    print(nltk.pos_tag(nltk.word_tokenize(sent)))

[('I', 'PRP')]
[('am', 'VBP')]
[('a', 'DT')]
[('human', 'NN')]
[('being', 'VBG')]
[(',', ',')]
[('capable', 'JJ')]
[('of', 'IN')]
[('doing', 'VBG')]
[('terrible', 'JJ')]
[('things', 'NNS')]


### Example 5 (Word2Vec: CBOW and Skip-gram)